# Generated by Django 4.1.4 on 2023-03-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
