# Generated by Django 4.1.4 on 2023-03-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers_app', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
