# Generated by Django 4.1.4 on 2023-03-13 04:19

import apps.adminusers_app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers_app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.adminusers_app.managers.USerManager()),
            ],
        ),
    ]
